# Generated by Django 3.0.2 on 2020-01-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesuser',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='codesuser',
            name='years_of_expirience',
        ),
        migrations.AddField(
            model_name='codesuser',
            name='experience',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='codesuser',
            name='interests',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='codesuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='codesuser',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='codesuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='codesuser',
            name='specification',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
