# Generated by Django 3.0.2 on 2020-01-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_auto_20200116_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesuser',
            name='real_name',
        ),
    ]
